### ISSUE TITLE
Adding KEYCHAIN_ACCESS_GROUP

### ISSUE THREAD

**Issue by LarsVoith** [Telerik-Verified-Plugins/Keychain-Sharing#1]
Looking for a way to add the variable in the config.xml (without command line) so the plugin could be used on build.phonegap

<platform name="ios">
        <preference name="KEYCHAIN_ACCESS_GROUP" value="1234"/>
    </platform>

Thanks!

**Comment by EddyVerbruggen** [comment]
You should be able to that this way:

``` xml
<plugin name="plugin-id" source="npm">
  <param name="KEYCHAIN_ACCESS_GROUP" value="your-value" />
<plugin>
```

**Comment by LarsVoith** [comment]
Thanks, I got it to build successfully (without errors) using your demo and making sure the Bundle Seed ID is identical for both apps. I was able to write and read but not share. Looks like the directions in the App is also referencing a "SHARED_BUNDLE_ID"  but i can find the documentation that references this. What should I do with this?

**Comment by EddyVerbruggen** [comment]
Are you referring to this doc? http://plugins.telerik.com/cordova/plugin/keychain-sharing

**Comment by LarsVoith** [comment]
yes

**Comment by LarsVoith** [comment]
I followed those docs, but it still seems like both apps are not sharing the same KEYCHAIN_ACCESS_GROUP

Both apps ("com.App1" and "com.App2") have this line in the config.xml
<plugin spec="https://github.com/Telerik-Verified-Plugins/Keychain-Sharing.git" source="git" >
    <param name="KEYCHAIN_ACCESS_GROUP" value="com.App1" />
  </plugin>

**Comment by LarsVoith** [comment]
![snip20160513_1](https://cloud.githubusercontent.com/assets/13261090/15250909/f04e76fa-18f4-11e6-9256-912e52e88b19.png)
Here is the snippet from my config.xml

**Comment by EddyVerbruggen** [comment]
That looks good to me.

Not sure about that `SHARED_BUNDLE_ID` myself, but can you check that you've configured the "Bundle Seed ID" correctly (see the doc).

**Comment by EddyVerbruggen** [comment]
Note that this plugin requires hooks to execute and that has only been tested with the Cordova CLI and Telerik Platform. I don't know for sure whether or not PGB applies them at all.

You can verify by checking the built `.ipa`; download it to a Mac, open the payload (right click in finder) and see if this file is there: https://github.com/Telerik-Verified-Plugins/Keychain-Sharing/blob/master/src/ios/resources/KeychainSharing.entitlements

**Comment by LarsVoith** [comment]
Thanks Eddy, you are right hooks can't be used - thats the problem. I m not sure if there is a work around to add entitlements.

**Comment by EddyVerbruggen** [comment]
Was afraid so.. I don't think there is a way to use pgbuild for that.. but you're better off asking that question on the pgbuild forums.
